name: "Task 3 - Deploy S3 via OIDC"

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'


permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    name: "Terraform Apply S3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::116981762429:role/github-oidc-s3-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve